# fly.toml app configuration file generated for planner on 2025-07-13T18:32:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tripmaxxing-planner"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "tripmaxxing_data"
  destination = "/data"

[metrics]
  port = 9091
  path = "/metrics" 